### ISSUE TITLE
[1] Sticky Header

### ISSUE THREAD

**Issue by tomahawk-pilot** [rebuildearth/openhack.tech#16]
Make the Header Sticky

**Comment by anhek** [comment]
Hi, I'd like to give a try on this one :)

**Comment by riginoommen** [comment]
@anhek Do you like to work on this issue?.

Suggested solution:

position:fixed on the header CSS

**Comment by anhek** [comment]
Yes

**Comment by riginoommen** [comment]
@anhek Please go ahead. Fork and continue

**Comment by tomahawk-pilot** [comment]
fixed
