### ISSUE TITLE
[1] add slack link

### ISSUE THREAD

**Issue by tomahawk-pilot** [rebuildearth/openhack.tech#20]
add slack link to join . https://join.slack.com/t/rebuildearth/shared_invite/enQtNzIyMTMwMjQ2MDg0LWEyY2U5ZmRmNTEzZWY2YTVhOTQ0N2MzMDcwY2ZkMjBkMWM2NjYyYjU5YzAxM2Y1ZTlhN2EzOGVhMWFjM2VhNjY

workspace url is rebuildearth.slack.com

add a note that people having an account in keralaresue.slack.com don't need to signup and use the old credentials.

**Comment by melvin2016** [comment]
Can I take up?

**Comment by raghav-ys** [comment]
@tomahawk-pilot @riginoommen- I would like to work on this issue. I have  a question though, where should we add the slack link. Is it separate divison or next to social media widgets on top right corner on the web page.

**Comment by avronr** [comment]
Fixed. Please close this issue.
