### ISSUE TITLE
changes to partnering organisations section

### ISSUE THREAD

**Issue by tomahawk-pilot** [rebuildearth/openhack.tech#48]
can we put KSITM and Government Logo, along with Github logo to the Sponsors Section and add Hack Club Logo to the partnering organizations section. #36 also raised for the same issue.

**Comment by AnnleeFores** [comment]
Google drive link to the logo from GitHub & Hack Club
https://drive.google.com/file/d/1jvnY0w7h_rgZcPf0hRKHfORRa2O-zxu8/view?usp=sharing

Link to Hack Club Website:  https://hackclub.com/

**Comment by tomahawk-pilot** [comment]
fixed
